version: "3"

services:
  next-app:
    container_name: next-raspberrypi-front
    build:
      context: ./next-app
      dockerfile: Dockerfile
    env_file:
      - .env.production.local
    restart: always
    ports:
      - 3000:3000